#!/usr/bin/env zsh

# movement
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'

# ls
alias ls='ls --color=auto'
alias la='ls -lA --color=auto'
alias ll='ls -l --color=auto'
alias l='ls -A --color=auto'

# git
alias g='git'
alias gitroot='cd $(git rev-parse --show-toplevel)'

# lazygit
alias lg='lazygit'

# shell
alias reload-zsh="source $HOME/.zshenv && source $ZDOTDIR/.zshrc"
alias path='echo -e ${PATH//:/\\n}'

# asdf
alias update-nvim-stable='asdf uninstall neovim stable && asdf install neovim stable'

# tmux-sessionizer
alias ts='tmux-sessionizer'
# tmux-browser
alias tb='tmux-browser'

# chezmoi
alias chz='chezmoi'

# ssh
alias ssha='ssh-add'
alias fix-ssh='eval $(tmux showenv -s SSH_AUTH_SOCK)'
