#!/bin/zsh

# XDG

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

# editor

export EDITOR="nvim"
export VISUAL="nvim"

# path

typeset -U PATH path
path=("$HOME/.arkade/bin" "$HOME/.local/bin" "$path[@]")
export PATH
