# Mise
[packages.mise.common]
fzf = "latest"
go = "latest"
jq = "latest"
k9s = "latest"
lazygit = "latest"
node = "latest"
terraform = "latest"
tmux = "latest"
uv = "latest"
yamlfmt = "latest"
yq = "latest"
neovim = "0.11.7"

[packages.mise.work]

[packages.mise.personal]
"github:anomalyco/opencode" = "latest"
