#!/usr/bin/env zsh

# Lines configured by zsh-newuser-install
setopt autocd nomatch
bindkey -v
# End of lines configured by zsh-newuser-install

# Manually added lines
# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Ignore dupes in .zhistory
setopt hist_ignore_all_dups

# Turn off annoying beeping
setopt nobeep

# Suggest similar command if mistyped
setopt correct

# Add custom completions to fpath
if [ -d "$ZDOTDIR/completions" ] ; then
    fpath=("$ZDOTDIR/completions" "$fpath[@]")
fi

# Simple .zshrc from wiki.archlinux.org
autoload -Uz compinit promptinit
compinit
promptinit

#zstyle ':completion:*' menu select

#autoload -Uz vcs_info
#precmd_vcs_info() { vcs_info }
#precmd_functions+=( precmd_vcs_info )
#setopt prompt_subst
#RPROMPT=\$vcs_info_msg_0_
#zstyle ':vcs_info:git:*' formats '%b'

# This will set the default prompt to the walters theme
prompt redhat

# Load aliases and any machince specific extras
for file in "$ZDOTDIR"/.zsh_{aliases,extra}; do
    [ -r "$file" ] && [ -f "$file" ] && source "$file";
done;

# For enabling git signing
export GPG_TTY=$(tty)
