#!/usr/bin/env zsh

# movement
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'

# ls
alias ls='ls --color=auto'
alias la='ls -lA --color=auto'
alias ll='ls -l --color=auto'
alias l='ls'

# git
alias g='git'

# shell
alias reload-zsh="source $HOME/.zshenv && source $ZDOTDIR/.zshrc"
alias path='echo -e ${PATH//:/\\n}'
