#!/usr/bin/env zsh

# ls
alias ls='ls --color=auto'
alias lla='ls -lA --color=auto'
alias ll='ls -l --color=auto'
alias la='ls -A --color=auto'
alias l='ls'

# git
alias g='git'
alias gs='git status'
alias ga='git add'
alias gp='git push'
alias gc='git commit'
alias gd='git diff'
alias gl='git log'
alias glo='git log --pretty="oneline"'
alias glol='git log --graph --oneline --decorate'
