#!/usr/bin/env zsh

# Lines configured by zsh-newuser-install
setopt autocd nomatch
bindkey -v
# End of lines configured by zsh-newuser-install

# Manually added lines
# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Ignore dupes in .zhistory
setopt hist_ignore_all_dups

# Turn off annoying beeping
setopt nobeep

# Suggest similar command if mistyped
setopt correct

# Add custom completions to fpath
if [ -d "$ZDOTDIR/completions" ] ; then
    fpath=("$ZDOTDIR/completions" "$fpath[@]")
fi

# Add custom prompts to fpath
if [ -d "$ZDOTDIR/prompts" ] ; then
    fpath=("$ZDOTDIR/prompts" "$fpath[@]")
fi

# Vi bindings for tab completion menu
zmodload zsh/complist
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history

# Configure compinit
autoload -Uz compinit
compinit

if [ -f "$ZDOTDIR/plugins/completion.zsh" ] ; then
    source "$ZDOTDIR/plugins/completion.zsh";
fi

# Add autosuggestions
if [ -f "$ZDOTDIR/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh" ] ; then
    ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#585858"
    source "$ZDOTDIR/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh"
fi

# Configure prompt
autoload -Uz promptinit
promptinit

# This will set the default prompt to the quivical theme
prompt quivical

# Load aliases and any machine specific extras
for file in "$ZDOTDIR"/.zsh_{aliases,funcs,extra}; do
    [ -r "$file" ] && [ -f "$file" ] && source "$file";
done;

# For enabling git signing
export GPG_TTY=$(tty)

# Add syntax highlighting
if [ -f "$ZDOTDIR/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" ] ; then
    source "$ZDOTDIR/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh";
fi
